/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as AgendaIndexRouteImport } from './routes/agenda.index'
import { Route as AgendaSlugRouteImport } from './routes/agenda.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminActivitesRouteImport } from './routes/_authenticated/admin.activites'
import { Route as AuthenticatedAdminActualitesRouteImport } from './routes/_authenticated/admin.actualites'
import { Route as AuthenticatedAdminEvenementsRouteImport } from './routes/_authenticated/admin.evenements'
import { Route as AuthenticatedAdminGalerieRouteImport } from './routes/_authenticated/admin.galerie'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminParametresRouteImport } from './routes/_authenticated/admin.parametres'
import { Route as AuthenticatedAdminRessourcesRouteImport } from './routes/_authenticated/admin.ressources'
import { Route as AuthenticatedAdminTemoignagesRouteImport } from './routes/_authenticated/admin.temoignages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaSlugRoute = AgendaSlugRouteImport.update({
  id: '/agenda/$slug',
  path: '/agenda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActivitesRoute =
  AuthenticatedAdminActivitesRouteImport.update({
    id: '/activites',
    path: '/activites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActualitesRoute =
  AuthenticatedAdminActualitesRouteImport.update({
    id: '/actualites',
    path: '/actualites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEvenementsRoute =
  AuthenticatedAdminEvenementsRouteImport.update({
    id: '/evenements',
    path: '/evenements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGalerieRoute =
  AuthenticatedAdminGalerieRouteImport.update({
    id: '/galerie',
    path: '/galerie',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParametresRoute =
  AuthenticatedAdminParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRessourcesRoute =
  AuthenticatedAdminRessourcesRouteImport.update({
    id: '/ressources',
    path: '/ressources',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemoignagesRoute =
  AuthenticatedAdminTemoignagesRouteImport.update({
    id: '/temoignages',
    path: '/temoignages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/ressources': typeof RessourcesRoute
  '/temoignages': typeof TemoignagesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/agenda/$slug': typeof AgendaSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/agenda/': typeof AgendaIndexRoute
  '/admin/activites': typeof AuthenticatedAdminActivitesRoute
  '/admin/actualites': typeof AuthenticatedAdminActualitesRoute
  '/admin/evenements': typeof AuthenticatedAdminEvenementsRoute
  '/admin/galerie': typeof AuthenticatedAdminGalerieRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/ressources': typeof AuthenticatedAdminRessourcesRoute
  '/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/ressources': typeof RessourcesRoute
  '/temoignages': typeof TemoignagesRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/agenda/$slug': typeof AgendaSlugRoute
  '/actualites': typeof ActualitesIndexRoute
  '/agenda': typeof AgendaIndexRoute
  '/admin/activites': typeof AuthenticatedAdminActivitesRoute
  '/admin/actualites': typeof AuthenticatedAdminActualitesRoute
  '/admin/evenements': typeof AuthenticatedAdminEvenementsRoute
  '/admin/galerie': typeof AuthenticatedAdminGalerieRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/ressources': typeof AuthenticatedAdminRessourcesRoute
  '/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activites': typeof ActivitesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/ressources': typeof RessourcesRoute
  '/temoignages': typeof TemoignagesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/agenda/$slug': typeof AgendaSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/agenda/': typeof AgendaIndexRoute
  '/_authenticated/admin/activites': typeof AuthenticatedAdminActivitesRoute
  '/_authenticated/admin/actualites': typeof AuthenticatedAdminActualitesRoute
  '/_authenticated/admin/evenements': typeof AuthenticatedAdminEvenementsRoute
  '/_authenticated/admin/galerie': typeof AuthenticatedAdminGalerieRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/_authenticated/admin/ressources': typeof AuthenticatedAdminRessourcesRoute
  '/_authenticated/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activites'
    | '/auth'
    | '/contact'
    | '/galerie'
    | '/qui-sommes-nous'
    | '/ressources'
    | '/temoignages'
    | '/admin'
    | '/actualites/$slug'
    | '/agenda/$slug'
    | '/actualites/'
    | '/agenda/'
    | '/admin/activites'
    | '/admin/actualites'
    | '/admin/evenements'
    | '/admin/galerie'
    | '/admin/messages'
    | '/admin/parametres'
    | '/admin/ressources'
    | '/admin/temoignages'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activites'
    | '/auth'
    | '/contact'
    | '/galerie'
    | '/qui-sommes-nous'
    | '/ressources'
    | '/temoignages'
    | '/actualites/$slug'
    | '/agenda/$slug'
    | '/actualites'
    | '/agenda'
    | '/admin/activites'
    | '/admin/actualites'
    | '/admin/evenements'
    | '/admin/galerie'
    | '/admin/messages'
    | '/admin/parametres'
    | '/admin/ressources'
    | '/admin/temoignages'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activites'
    | '/auth'
    | '/contact'
    | '/galerie'
    | '/qui-sommes-nous'
    | '/ressources'
    | '/temoignages'
    | '/_authenticated/admin'
    | '/actualites/$slug'
    | '/agenda/$slug'
    | '/actualites/'
    | '/agenda/'
    | '/_authenticated/admin/activites'
    | '/_authenticated/admin/actualites'
    | '/_authenticated/admin/evenements'
    | '/_authenticated/admin/galerie'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/parametres'
    | '/_authenticated/admin/ressources'
    | '/_authenticated/admin/temoignages'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivitesRoute: typeof ActivitesRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GalerieRoute: typeof GalerieRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  RessourcesRoute: typeof RessourcesRoute
  TemoignagesRoute: typeof TemoignagesRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  AgendaSlugRoute: typeof AgendaSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$slug': {
      id: '/agenda/$slug'
      path: '/agenda/$slug'
      fullPath: '/agenda/$slug'
      preLoaderRoute: typeof AgendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activites': {
      id: '/_authenticated/admin/activites'
      path: '/activites'
      fullPath: '/admin/activites'
      preLoaderRoute: typeof AuthenticatedAdminActivitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/actualites': {
      id: '/_authenticated/admin/actualites'
      path: '/actualites'
      fullPath: '/admin/actualites'
      preLoaderRoute: typeof AuthenticatedAdminActualitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/evenements': {
      id: '/_authenticated/admin/evenements'
      path: '/evenements'
      fullPath: '/admin/evenements'
      preLoaderRoute: typeof AuthenticatedAdminEvenementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/galerie': {
      id: '/_authenticated/admin/galerie'
      path: '/galerie'
      fullPath: '/admin/galerie'
      preLoaderRoute: typeof AuthenticatedAdminGalerieRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parametres': {
      id: '/_authenticated/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AuthenticatedAdminParametresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ressources': {
      id: '/_authenticated/admin/ressources'
      path: '/ressources'
      fullPath: '/admin/ressources'
      preLoaderRoute: typeof AuthenticatedAdminRessourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/temoignages': {
      id: '/_authenticated/admin/temoignages'
      path: '/temoignages'
      fullPath: '/admin/temoignages'
      preLoaderRoute: typeof AuthenticatedAdminTemoignagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivitesRoute: typeof AuthenticatedAdminActivitesRoute
  AuthenticatedAdminActualitesRoute: typeof AuthenticatedAdminActualitesRoute
  AuthenticatedAdminEvenementsRoute: typeof AuthenticatedAdminEvenementsRoute
  AuthenticatedAdminGalerieRoute: typeof AuthenticatedAdminGalerieRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminParametresRoute: typeof AuthenticatedAdminParametresRoute
  AuthenticatedAdminRessourcesRoute: typeof AuthenticatedAdminRessourcesRoute
  AuthenticatedAdminTemoignagesRoute: typeof AuthenticatedAdminTemoignagesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivitesRoute: AuthenticatedAdminActivitesRoute,
  AuthenticatedAdminActualitesRoute: AuthenticatedAdminActualitesRoute,
  AuthenticatedAdminEvenementsRoute: AuthenticatedAdminEvenementsRoute,
  AuthenticatedAdminGalerieRoute: AuthenticatedAdminGalerieRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminParametresRoute: AuthenticatedAdminParametresRoute,
  AuthenticatedAdminRessourcesRoute: AuthenticatedAdminRessourcesRoute,
  AuthenticatedAdminTemoignagesRoute: AuthenticatedAdminTemoignagesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivitesRoute: ActivitesRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GalerieRoute: GalerieRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  RessourcesRoute: RessourcesRoute,
  TemoignagesRoute: TemoignagesRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  AgendaSlugRoute: AgendaSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  AgendaIndexRoute: AgendaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
